# Generated by Django 5.2.1 on 2025-06-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in lists and APIs'),
        ),
    ]
