# Generated by Django 5.2.1 on 2025-06-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_size_options_size_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
